### ISSUE TITLE
[Enhancement] Have addon set assetUrl path under config.js for you

### ISSUE THREAD

**Issue by DanielOchoa** [poetic/ember-cli-github-pages#12]
In order to have any assets you have in your repo load correctly you need to add the following to your tests/dummy/config/environment.js file:
```
if (environment === 'production') {
  ENV.baseURL = '/name-of-your-repo'
}
```

This addon should append this for you, so you do not forget to do it yourself.

**Comment by jhr007** [comment]
Semantically, a lot of the auto configuration things could be moved to an environment of `gh-pages`
if ( environment === 'gh-pages' )  {
   ENV.baseURL = '/name-of-repo'
}

**Comment by jhr007** [comment]
It looks like the addon tries to do this for you in https://github.com/poetic/ember-cli-github-pages/blob/master/blueprints/ember-cli-github-pages/index.js#L36

But for addons the path should be `tests/dummy/config/environment.js`

To me it's a little over reaching to replace every instance in someone else's code. 

I think it would be better to append this before `return ENV;`

```javascript
  if (environment === 'gh-pages') {
    ENV.baseURL = '/' + require('../../../package.json')['name'];
  }
```

I also think long term this addon could make gh-pages from any ember app. The `ember github-pages:commit` doesn't do anything specific for ember addons.

**Comment by knownasilya** [comment]
See the PR I just submitted. It should work for apps and addons. Although only tested on an addon.

**Comment by knownasilya** [comment]
This should work as of v0.0.7
