### ISSUE TITLE
Not working with ember-cli 0.2.3

### ISSUE THREAD

**Issue by spruce** [poetic/ember-cli-github-pages#13]
Hey,
just wanted to let users know that this plugin is currently not working with ember-cli 0.2.3

I asked if it can be fixed in this repo or ember-cli. See here:
https://github.com/ember-cli/ember-cli/issues/3860

**Comment by DanielOchoa** [comment]
It looks like another pull request solves the issue. I'll take a closer look at this sometime this week.

**Comment by ahouchens** [comment]
Verified it does not work in ember-cli 0.2.3 also. Looking forward to a fix!

**Comment by ynnoj** [comment]
:+1:

**Comment by DanielOchoa** [comment]
I'll take a jab a it sometime this week :+1:

**Comment by Robdel12** [comment]
Looks like it was fixed in: https://github.com/ember-cli/ember-cli/pull/3845

**Comment by DanielOchoa** [comment]
I'll close it then.

**Comment by Robdel12** [comment]
I tested it out last night and forgot to report back. It works. Just gotta wait for 0.2.4 :P
