### ISSUE TITLE
Instructions for windows.

### ISSUE THREAD

**Issue by QuantumInformation** [poetic/ember-cli-github-pages#14]
If possible can you update the Readme to say what directories to leave in windows as by default `rf` is not a command.

**Comment by DanielOchoa** [comment]
This would be a good idea. Yes it is possible. I don't have access to windows and I'm to lazy to set it up on a virtual machine, so, I'll leave this as a pending fix for now.

**Comment by QuantumInformation** [comment]
I've switched to mac now, issue not there :)
