### ISSUE TITLE
subsequent command fails

### ISSUE THREAD

**Issue by knownasilya** [poetic/ember-cli-github-pages#2]
After running the command the first time, I wanted to update and run it again, but got this.

```no-highlight
ember gh-pages:commit --message "Fix dummy path"
version: 0.1.1
Command failed:
Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

Is it dependent on a different version of ember-cli?

**Comment by nahtnam** [comment]
Same issue here. @jakecraige Do you have any solution for this?

**Comment by knownasilya** [comment]
I haven't recently seen this issue myself, what about you @nahtnam?

**Comment by nahtnam** [comment]
Sorry, not using this plugin anymore.
