### ISSUE TITLE
Switch back to previous branch

### ISSUE THREAD

**Issue by jhr007** [poetic/ember-cli-github-pages#24]
At the end of the github-pages:commit this addon leaves the git repo on the gh-pages branch. 

I think it should switch back to the previous branch, like this command ran completely in the background. :grinning:

**Comment by jhr007** [comment]
This is best command I found that picks out the last checkout for branch/tags/git-hashes
`git reflog HEAD | grep 'checkout:' | head -1 | rev | cut -d' ' -f1 | rev`

http://stackoverflow.com/questions/6245570/how-to-get-current-branch-name-in-git

**Comment by truenorth** [comment]
at the end of the command, you also have to push your changes to github. It seems like it was a design decision to not actually do the push with this addon.

You could always make your own shell script like

```sh
ember github-pages:commit --message $1 && git push && cd -
```
or something

**Comment by jhr007** [comment]
True, but you can push a branch from any branch...
 `git push origin gh-pages`

I think the reasoning/need for having the user do it manually is because in many cases it requires user/pass input for the upload, and the git commands are strictly headless. 

https://github.com/poetic/ember-cli-github-pages/blob/master/lib/commands/commit.js#L61

**Comment by jhr007** [comment]
I originally thought of using the previous command to get the branch, store in JavaScript, then use it to checkout that branch at the end, but the `runCommand` function only handles stdin for debugging. 

There's probably a more elegant solution but this command works to get the previous branch. 
` git reflog HEAD | grep 'checkout' | head -2 | tail -1 | rev | cut -d' ' -f1 | rev `

I'll put some code together.

**Comment by jhr007** [comment]
This command should toggle back and forth between the last branches. 

```
git checkout `git reflog  HEAD | sed -n '/checkout/ !d; s/.* \(\S*\)$/\1/;p' | sed '2 !d'`
```

**Comment by osxi** [comment]
Fixed by https://github.com/poetic/ember-cli-github-pages/pull/29
