### ISSUE TITLE
Check addon for DemoURL

### ISSUE THREAD

**Issue by jhr007** [poetic/ember-cli-github-pages#27]
This would help increase awareness for demo apps, and would help developers looking for addons since emberaddons.com displays a button to the addon's demo. 

This would be in case someone is using this addon and doesn't know about `package.json['ember-addon']['demoURL']` let them know. 

This would add an annoying factor, but it could check for `disableDemoURLNotice` or something somewhere.

**Comment by osxi** [comment]
@jhr007 Clearly wording this in it's own section of the README would be a good PR.
