### ISSUE TITLE
Page not found when reload the page

### ISSUE THREAD

**Issue by matheusdavidson** [poetic/ember-cli-github-pages#3]
I have just placed an app on github pages and i found a problem with urls:

Github pages seems not to recognize url without "#", if you navigate trought the app clicking on the links it works, but if you refresh the page it shows 404 page, did you have this problem?

**Comment by elwayman02** [comment]
@jakecraige for some reason the blueprint did not work when installed in an addon...maybe it is not looking at `tests/dummy/config/environment.js`?

What I found to be a slicker solution was to simple add `ENV.locationType = 'hash';` inside the `if (environment === 'production')` block (same as how you have to set `ENV.baseURL`). IMO that is a better solution than this addon assuming that the user wants to use hash locations in all environments.

**Comment by knownasilya** [comment]
Both of those settings are updated with the latest version of the addon. It should also automatically update your dummy config.

**Comment by notngan** [comment]
@matheusdavidson Awesome! 🤪 Feels I’m a hacker now!
