### ISSUE TITLE
Directly requesting sub routes causes 404

### ISSUE THREAD

**Issue by Matt-Jensen** [poetic/ember-cli-github-pages#32]
Not sure if there is a good fix for this but I'm seeing this in multiple repos (including my own):
http://matt-jensen.github.io/ember-cli-g-maps/setup/index

and
http://ravellaw.github.io/e3/bubble-1

Should be seeing 404.

**Comment by mike-north** [comment]
make sure you set `ENV.locationType = 'hash';` in your **config/environment.js**. This is a special thing you have to do for github pages

**Comment by Matt-Jensen** [comment]
This is a good solution. I've successfully implemented it. Thank you.

What do you think about having a FAQ section in the readme for this?  Don't want this fix getting lost when I close.

**Comment by mike-north** [comment]
IMO it should be part of the blueprint. If you were publishing an ember app (as opposed to an ember-addon) to github pages, [it would be done for you as part of addon installation](https://github.com/poetic/ember-cli-github-pages/blob/master/blueprints/ember-cli-github-pages/index.js#L21-L24). I think we just need an additional blueprint for the ember-addon demo app use case like yours.

**Comment by Matt-Jensen** [comment]
Agreed.  Looks like this will be the default in the future, as it should be.  Thank you for your help @mike-north!
