### ISSUE TITLE
`returnToPreviousCheckout` doesn't work

### ISSUE THREAD

**Issue by offirgolan** [poetic/ember-cli-github-pages#39]
See [lib/commands/commit.js#L51-L55](https://github.com/poetic/ember-cli-github-pages/blob/master/lib/commands/commit.js#L51-L55)

The command to checkout previous branch doen't work

**Comment by offirgolan** [comment]
Doing the following might be simpler

```js
function returnToPreviousCheckout() {
  return runCommand("git checkout -", execOptions);
}
```

`git checkout -` is a shorthand for `git checkout @{-1}`.

**Comment by osxi** [comment]
Yeah you're absolutely right. I think we just didn't know about that at the time.
