### ISSUE TITLE
Comaintainers needed

### ISSUE THREAD

**Issue by MatthewHager** [poetic/ember-cli-github-pages#42]
If anyone is interested in helping us maintain this repo, please let me know. We have a small team and way too many open source repos and unfrotuantely many are getting neglected if they don't pertain to a project on which we are actively working.

Please reply and let me know if you'd be intersted in helping out. If you are a freelancer or work for a comapny and help out, we'd be more than happy to accept PR on the README to give yourself credit for helping out with this project.

Thanks!

**Comment by knownasilya** [comment]
Sign me up, I use this addon all the time.

**Comment by MatthewHager** [comment]
Awesome. Done. What is your handle on NPM?

**Comment by knownasilya** [comment]
knownasilya
