### ISSUE TITLE
ember-bootstrap assets not loading

### ISSUE THREAD

**Issue by benoror** [poetic/ember-cli-github-pages#45]
Hi! I am learning Ember and made a **User Page** which I deployed recently. Unfortunately some of the **assets are not loading correctly**:

- Page: http://benoror.github.io/
- Repo: https://github.com/benoror/benoror.github.io

I believe the images in the front page are not correctly loaded since they're dynamically created ({{#each...}} statement) on runtime (https://github.com/poetic/ember-cli-github-pages/issues/10).

What struggles me the most is Bootstrap (CSS/JS), since I installed it using [kaliber5.github.io/ember-bootstrap/](http://kaliber5.github.io/ember-bootstrap/), as you can see in the console I get the following error:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://benoror.github.io/assets/vendor-e90b85f169eb47329513c2253e3333e2.css' with computed SHA-256 integrity 'sRY8jSb2DsMAa3f+lwjxvBco2xC14NPhem5cOEm20rc='. The resource has been blocked.
http://benoror.github.io/assets/social/email.png Failed to load resource: the server responded with a status of 404 (Not Found)
```

Any help would be greatly appreciated :smile_cat:

**Comment by knownasilya** [comment]
You need to disable fingerprinting for dynamically loaded images, since pages creates a production build.

**Comment by benoror** [comment]
@knownasilya Gotcha, thanks for the tip! :smile:  Found the docs here:

http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls

Fixed with:

```
  var app = new EmberApp(defaults, {
    fingerprint: {
      exclude: ['assets/social']
    }
  });
```

Still struggling with bootstrap though

**Comment by benoror** [comment]
Found the issue:

- http://discuss.emberjs.com/t/ember-app-wont-load-resource-integrity-error-in-chrome/8733
- https://github.com/jonathanKingston/ember-cli-sri/issues/5

Hacky fix:

```
<script integrity=""...>
```
