### ISSUE TITLE
Command hangs

### ISSUE THREAD

**Issue by xdumaine** [poetic/ember-cli-github-pages#47]
when I run `ember github-pages:commit --message "my commit"` I get this singular output, and nothing happens: 

```text
version: 2.3.0
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
```

Do you have any advice for debugging this?

**Comment by knownasilya** [comment]
So it runs `ember build -prod` when you do that, so see if that command works for you.

**Comment by xdumaine** [comment]
Looks like that's what's hanging. Investigating why. If you have any info on that I'd appreciate it. Most issues I can find are just closed for being stale, with no resolution.

**Comment by knownasilya** [comment]
What version of node? Did you just do an upgrade of the cli (maybe a missing dependency change)?

**Comment by xdumaine** [comment]
```text
$ ember -v
version: 2.3.0
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 4.4.0
os: darwin x64
```

**Comment by knownasilya** [comment]
Try `rm -rf node_modules bower_components tmp dist` and `npm install && bower install`

**Comment by xdumaine** [comment]
Was actually just trying that. Doesn't seem to help. There are some posts indicating that `fingerprint` can be a culprit, but even adding exclude/ignore to all of my modules, I get the hang. Very strange.
