### ISSUE TITLE
Does this work with the new rootURL?

### ISSUE THREAD

**Issue by rwwagner90** [poetic/ember-cli-github-pages#51]
Seems that Ember CLI has removed baseURL and moved to rootURL. I am now unable to deploy my apps. Please advise.

**Comment by knownasilya** [comment]
Thanks for letting me know, I'll have a look.

**Comment by knownasilya** [comment]
In the mean time you might be able to just update your dummy app's config to set the `rootURL` instead.

**Comment by knownasilya** [comment]
Should be fixed as of v0.1.2

**Comment by rwwagner90** [comment]
Awesome, thanks @knownasilya!
