### ISSUE TITLE
Checkbox tick png missing on demo site

### ISSUE THREAD

**Issue by pollingj** [poetic/ember-cli-github-pages#53]
If you click on the checkbox the tick does not appear.

https://sauce-consultants.github.io/ember-sauce-material-design/#/forms

**Comment by knownasilya** [comment]
How are you defining the image? If you do it dynamically, you need to remove the image from fingerprinting, see https://github.com/poetic/ember-cli-github-pages#some-of-my-assets-images-arent-showing-up-what-do-i-do

**Comment by pollingj** [comment]
Sorry, please ignore, did this late at night, and in the completely wrong github project ;)
