### ISSUE TITLE
Ember 2.18 deprecation

### ISSUE THREAD

**Issue by tomwayson** [poetic/ember-cli-github-pages#60]
I'm getting the following deprecation after upgrading my app to Ember 2.18 and it appears to be coming from this addon:

https://github.com/Esri/ember-cli-cedar/pull/73/commits/60f340dbe36ea2f91f63ca2976e84b9773c9c981

It seems related to https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902

It looks like [you've already upgraded ember-cli-dependency-checker (it's in both depenencies and devDependencies actually)](https://github.com/poetic/ember-cli-github-pages/blob/6e63b396aff2d56df073eaf88cb3dd49a777ad78/package.json#L26-L32), but just haven't done a release yet.

I did a quick test by updating my package.json to point to master w/ `"ember-cli-github-pages": "poetic/ember-cli-github-pages"`and re-installed, and I no longer see the deprecation,so I think that if you are able to just release master as is that would fix this issue.

**Comment by knownasilya** [comment]
I've just released v0.2.0. Give it a try.

**Comment by tomwayson** [comment]
Thanks @knownasilya! Bumping to 0.2.0 removes the warning.
