### ISSUE TITLE
Fails if the default bash is FISH

### ISSUE THREAD

**Issue by mayank8318** [poetic/ember-cli-github-pages#64]

**Comment by knownasilya** [comment]
Is there a specific error?

**Comment by mayank8318** [comment]
@knownasilya Yes in the `runComman()` method `&&` is causing the problem. FISH requires it to be `; and`. Sorry didn't mention that

**Comment by knownasilya** [comment]
I probably won't be able to get to this issue this week, but would be able to review a PR if you feel up to it.

**Comment by mayank8318** [comment]
@knownasilya I will try if I can find a fix. I fixed it by Find and Replace (there are only 3 occurrences). But I am not sure if this will work on other terminals. Worked on FISH

**Comment by knownasilya** [comment]
You might have to do a conditional to check if using fish and use alternate syntax.

**Comment by mayank8318** [comment]
@knownasilya Yes, I will try to solve it and open a PR if I am successful. I will let you know :)

**Comment by devotox** [comment]
Fixes here
https://github.com/poetic/ember-cli-github-pages/pull/66

**Comment by NathanJang** [comment]
Hi all, I have made a PR at #67, which tries to fix the issue more gracefully. It appears to work so far for my use cases. Please let me know if there are any issues.
