### ISSUE TITLE
Missing quote bug fix for 'hash' is not available in latest tagged version hence npm

### ISSUE THREAD

**Issue by kushdilip** [poetic/ember-cli-github-pages#8]
I am talking about below commit, which is not available through npm.
https://github.com/poetic/ember-cli-github-pages/commit/c36533aeefb5cb038183b9598431c431cb09b0e9

**Comment by DanyHunter** [comment]
https://github.com/poetic/ember-cli-github-pages/tree/v0.0.4 is now on npm.
