### ISSUE TITLE
Cannot find assets

### ISSUE THREAD

**Issue by rwwagner90** [poetic/ember-cli-github-pages#9]
My page will not load any of my assets. I saw this issue: https://github.com/ember-cli/ember-cli/issues/398. Does that apply here? If not, why do my assets not load? https://github.com/rwwagner90/ember-shepherd/tree/gh-pages

**Comment by DanyHunter** [comment]
Adding the following to your `tests/dummy/config/environment.js` file will add the right path to your assets:
```javascript
  if (environment === 'production') {
    ENV.baseURL = '/name-of-your-repo'
  }
```

**Comment by rwwagner90** [comment]
@DanyHunter awesome, that worked. Thanks! Should we add that to the Readme?

**Comment by DanyHunter** [comment]
Definitely. I'll go ahead and make a quick edit then I'll close this issue.

**Comment by DanyHunter** [comment]
Instructions are now on the readme. f6f248d54a86efca952bcc212be5425860b087e0
